name: Waka Readme

on:
  schedule:
    - cron: '25 5 1 * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
